"""engine phase 1a schema

Revision ID: 63446a371e5a
Revises: d29b3ede11f0
Create Date: 2026-08-26 20:38:45.241890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# NOTE: money columns use app.engine_models.MinorAmount in the ORM, a TypeDecorator
# whose impl IS BigInteger. The migration deliberately spells the underlying
# sa.BigInteger() instead of importing app code: the emitted DDL is identical and
# the migration stays self-contained (app code may change; this revision may not).

# revision identifiers, used by Alembic.
revision: str = '63446a371e5a'
down_revision: Union[str, Sequence[str], None] = 'd29b3ede11f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ── Invariant 3: frozen layout versions are immutable ───────────────────────
# Autogenerate cannot produce triggers, so they are written by hand here.
#
# Two rules, both enforced by the DATABASE (spec 2, exit test 5):
#   1. UPDATE of layout_data is rejected while status = 'frozen'.
#   2. status may go draft -> frozen, but never frozen -> draft.
# Freezing itself still works: at that moment OLD.status is still 'draft'.
#
# Postgres raises via plpgsql (surfaces as sqlalchemy.exc.InternalError); SQLite
# raises via RAISE(ABORT) (surfaces as sqlalchemy.exc.IntegrityError). Both are
# sqlalchemy.exc.DBAPIError, which is what the tests assert on.

_PG_FUNCTION = """
CREATE OR REPLACE FUNCTION engine_layout_versions_freeze_guard()
RETURNS trigger AS $$
BEGIN
    IF OLD.status = 'frozen'
       AND NEW.layout_data IS DISTINCT FROM OLD.layout_data THEN
        RAISE EXCEPTION
            'engine_layout_versions.layout_data is immutable once frozen (id=%)',
            OLD.id;
    END IF;
    IF OLD.status = 'frozen' AND NEW.status <> 'frozen' THEN
        RAISE EXCEPTION
            'engine_layout_versions cannot leave the frozen state (id=%)',
            OLD.id;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

_PG_TRIGGER = """
CREATE TRIGGER trg_engine_layout_versions_freeze_guard
BEFORE UPDATE ON engine_layout_versions
FOR EACH ROW EXECUTE FUNCTION engine_layout_versions_freeze_guard();
"""

# SQLite has no procedural language; the same two rules become two guarded triggers.
# `IS NOT` is SQLite's null-safe inequality, matching Postgres IS DISTINCT FROM.
_SQLITE_IMMUTABLE = """
CREATE TRIGGER trg_engine_layout_versions_immutable
BEFORE UPDATE OF layout_data ON engine_layout_versions
FOR EACH ROW WHEN OLD.status = 'frozen' AND NEW.layout_data IS NOT OLD.layout_data
BEGIN
    SELECT RAISE(ABORT,
        'engine_layout_versions.layout_data is immutable once frozen');
END;
"""

_SQLITE_NO_UNFREEZE = """
CREATE TRIGGER trg_engine_layout_versions_no_unfreeze
BEFORE UPDATE OF status ON engine_layout_versions
FOR EACH ROW WHEN OLD.status = 'frozen' AND NEW.status <> 'frozen'
BEGIN
    SELECT RAISE(ABORT,
        'engine_layout_versions cannot leave the frozen state');
END;
"""


def _install_freeze_guard() -> None:
    dialect = op.get_bind().dialect.name
    if dialect == "postgresql":
        op.execute(_PG_FUNCTION)
        op.execute(_PG_TRIGGER)
    elif dialect == "sqlite":
        op.execute(_SQLITE_IMMUTABLE)
        op.execute(_SQLITE_NO_UNFREEZE)
    else:
        raise RuntimeError(
            f"No layout-version freeze guard implemented for dialect {dialect!r}. "
            "Invariant 3 would be unenforced; refusing to migrate silently."
        )


def _drop_freeze_guard() -> None:
    dialect = op.get_bind().dialect.name
    if dialect == "postgresql":
        op.execute(
            "DROP TRIGGER IF EXISTS trg_engine_layout_versions_freeze_guard "
            "ON engine_layout_versions"
        )
        op.execute("DROP FUNCTION IF EXISTS engine_layout_versions_freeze_guard()")
    elif dialect == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS trg_engine_layout_versions_immutable")
        op.execute("DROP TRIGGER IF EXISTS trg_engine_layout_versions_no_unfreeze")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_organizations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), server_default='personal', nullable=False),
    sa.Column('plan', sa.Text(), server_default='personal', nullable=False),
    sa.Column('branding', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("plan IN ('personal', 'business', 'pro', 'enterprise')", name='ck_engine_organizations_plan'),
    sa.CheckConstraint("status IN ('active', 'suspended')", name='ck_engine_organizations_status'),
    sa.CheckConstraint("type IN ('personal', 'business')", name='ck_engine_organizations_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_organizations_slug'), ['slug'], unique=True)

    op.create_table('engine_api_keys',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('key_prefix', sa.Text(), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('environment', sa.Text(), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("environment IN ('sandbox', 'production')", name='ck_engine_api_keys_environment'),
    sa.ForeignKeyConstraint(['organization_id'], ['engine_organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_api_keys_key_prefix'), ['key_prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_api_keys_organization_id'), ['organization_id'], unique=False)

    op.create_table('engine_memberships',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'event_manager', 'venue_manager', 'box_office', 'finance', 'support', 'scanner', 'marketing')", name='ck_engine_memberships_role'),
    sa.CheckConstraint("status IN ('active', 'invited', 'disabled')", name='ck_engine_memberships_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['engine_organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_engine_memberships_org_user')
    )
    with op.batch_alter_table('engine_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('engine_venues',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('address_ar', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), server_default='Asia/Kuwait', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['engine_organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_venues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_venues_organization_id'), ['organization_id'], unique=False)

    op.create_table('engine_webhook_endpoints',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('events', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['engine_organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_webhook_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_webhook_endpoints_organization_id'), ['organization_id'], unique=False)

    op.create_table('engine_audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_api_key_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_api_key_id'], ['engine_api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['engine_organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_audit_log_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_audit_log_organization_id'), ['organization_id'], unique=False)

    op.create_table('engine_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('venue_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_ar', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_ar', sa.Text(), nullable=True),
    sa.Column('artwork_url', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('cast', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('policies', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'coming_soon', 'scheduled', 'cancelled', 'archived')", name='ck_engine_events_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['engine_organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venue_id'], ['engine_venues.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_events_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_events_venue_id'), ['venue_id'], unique=False)

    op.create_table('engine_venue_layouts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('venue_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['engine_venues.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_venue_layouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_venue_layouts_venue_id'), ['venue_id'], unique=False)

    op.create_table('engine_webhook_deliveries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('endpoint_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'delivered', 'failed')", name='ck_engine_webhook_deliveries_status'),
    sa.CheckConstraint('attempts >= 0', name='ck_engine_webhook_deliveries_attempts'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['engine_webhook_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_webhook_deliveries_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_webhook_deliveries_status'), ['status'], unique=False)

    op.create_table('engine_layout_versions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('venue_layout_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('layout_data', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'frozen')", name='ck_engine_layout_versions_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venue_layout_id'], ['engine_venue_layouts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_layout_id', 'version_number', name='uq_engine_layout_versions_layout_version')
    )
    with op.batch_alter_table('engine_layout_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_layout_versions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_layout_versions_venue_layout_id'), ['venue_layout_id'], unique=False)

    op.create_table('engine_performances',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('layout_version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('doors_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('sales_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sales_close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('box_office_close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'on_sale', 'paused', 'sold_out', 'closed', 'cancelled')", name='ck_engine_performances_status'),
    sa.ForeignKeyConstraint(['event_id'], ['engine_events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['layout_version_id'], ['engine_layout_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_performances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_performances_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_performances_layout_version_id'), ['layout_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_performances_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_performances_status'), ['status'], unique=False)

    op.create_table('engine_orders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('performance_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('customer_name', sa.Text(), nullable=True),
    sa.Column('customer_email', sa.Text(), nullable=True),
    sa.Column('customer_phone', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extended', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('subtotal_minor', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('fees_minor', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('discount_minor', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('external_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("channel IN ('marketplace', 'api', 'box_office', 'comp', 'invitation')", name='ck_engine_orders_channel'),
    sa.CheckConstraint("status IN ('draft', 'awaiting_payment', 'completed', 'expired', 'cancelled')", name='ck_engine_orders_status'),
    sa.CheckConstraint('discount_minor >= 0', name='ck_engine_orders_discount_minor_non_negative'),
    sa.CheckConstraint('fees_minor >= 0', name='ck_engine_orders_fees_minor_non_negative'),
    sa.CheckConstraint('length(currency) = 3', name='ck_engine_orders_currency_len'),
    sa.CheckConstraint('subtotal_minor >= 0', name='ck_engine_orders_subtotal_minor_non_negative'),
    sa.CheckConstraint('total_minor >= 0', name='ck_engine_orders_total_minor_non_negative'),
    sa.ForeignKeyConstraint(['organization_id'], ['engine_organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['performance_id'], ['engine_performances.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_orders_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_orders_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_orders_performance_id'), ['performance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_orders_status'), ['status'], unique=False)
        batch_op.create_index('uq_engine_orders_org_external_ref', ['organization_id', 'external_ref'], unique=True, postgresql_where=sa.text('external_ref IS NOT NULL'), sqlite_where=sa.text('external_ref IS NOT NULL'))

    op.create_table('engine_performance_categories',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('performance_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('category_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount_minor >= 0', name='ck_engine_performance_categories_amount_minor_non_negative'),
    sa.CheckConstraint('length(currency) = 3', name='ck_engine_performance_categories_currency_len'),
    sa.ForeignKeyConstraint(['performance_id'], ['engine_performances.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('performance_id', 'category_key', name='uq_engine_performance_categories_perf_key')
    )
    with op.batch_alter_table('engine_performance_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_performance_categories_performance_id'), ['performance_id'], unique=False)

    op.create_table('engine_performance_seats',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('performance_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('seat_uid', sa.Text(), nullable=False),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('row_label', sa.Text(), nullable=True),
    sa.Column('seat_number', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('category_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='available', nullable=False),
    sa.Column('price_override_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), nullable=True),
    sa.Column('accessibility', sa.Boolean(), server_default=sa.text('(false)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'blocked', 'invitation', 'reserved_internal')", name='ck_engine_performance_seats_status'),
    sa.CheckConstraint('price_override_minor >= 0', name='ck_engine_performance_seats_price_override_minor_non_negative'),
    sa.ForeignKeyConstraint(['performance_id'], ['engine_performances.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('performance_id', 'seat_uid', name='uq_engine_performance_seats_perf_seat_uid')
    )
    with op.batch_alter_table('engine_performance_seats', schema=None) as batch_op:
        batch_op.create_index('ix_engine_performance_seats_perf_status', ['performance_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_performance_seats_performance_id'), ['performance_id'], unique=False)

    op.create_table('engine_seat_locks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('performance_seat_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['engine_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['performance_seat_id'], ['engine_performance_seats.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_seat_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_seat_locks_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_seat_locks_performance_seat_id'), ['performance_seat_id'], unique=False)
        batch_op.create_index('uq_engine_seat_locks_active_seat', ['performance_seat_id'], unique=True, postgresql_where=sa.text('released_at IS NULL'), sqlite_where=sa.text('released_at IS NULL'))

    op.create_table('engine_tickets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('performance_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('performance_seat_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('status', sa.Text(), server_default='issued', nullable=False),
    sa.Column('credential_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('credential_hash', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by_user_id', sa.Integer(), nullable=True),
    sa.Column('amount_paid_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('issued', 'checked_in', 'cancelled', 'refunded')", name='ck_engine_tickets_status'),
    sa.CheckConstraint('amount_paid_minor >= 0', name='ck_engine_tickets_amount_paid_minor_non_negative'),
    sa.CheckConstraint('credential_version >= 1', name='ck_engine_tickets_credential_version_positive'),
    sa.CheckConstraint('length(currency) = 3', name='ck_engine_tickets_currency_len'),
    sa.ForeignKeyConstraint(['checked_in_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['engine_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['engine_organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['performance_id'], ['engine_performances.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['performance_seat_id'], ['engine_performance_seats.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_tickets_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_tickets_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_tickets_performance_id'), ['performance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_tickets_performance_seat_id'), ['performance_seat_id'], unique=False)
        batch_op.create_index('uq_engine_tickets_live_seat', ['performance_seat_id'], unique=True, postgresql_where=sa.text("status IN ('issued', 'checked_in')"), sqlite_where=sa.text("status IN ('issued', 'checked_in')"))

    op.create_table('engine_usage_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=False), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ticket_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['engine_organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['engine_tickets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    with op.batch_alter_table('engine_usage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_usage_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_usage_events_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###

    # Invariant 3 - not expressible via autogenerate.
    _install_freeze_guard()


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the trigger first: it depends on the table below.
    _drop_freeze_guard()

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engine_usage_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_usage_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_engine_usage_events_occurred_at'))

    op.drop_table('engine_usage_events')
    with op.batch_alter_table('engine_tickets', schema=None) as batch_op:
        batch_op.drop_index('uq_engine_tickets_live_seat', postgresql_where=sa.text("status IN ('issued', 'checked_in')"), sqlite_where=sa.text("status IN ('issued', 'checked_in')"))
        batch_op.drop_index(batch_op.f('ix_engine_tickets_performance_seat_id'))
        batch_op.drop_index(batch_op.f('ix_engine_tickets_performance_id'))
        batch_op.drop_index(batch_op.f('ix_engine_tickets_organization_id'))
        batch_op.drop_index(batch_op.f('ix_engine_tickets_order_id'))

    op.drop_table('engine_tickets')
    with op.batch_alter_table('engine_seat_locks', schema=None) as batch_op:
        batch_op.drop_index('uq_engine_seat_locks_active_seat', postgresql_where=sa.text('released_at IS NULL'), sqlite_where=sa.text('released_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_engine_seat_locks_performance_seat_id'))
        batch_op.drop_index(batch_op.f('ix_engine_seat_locks_order_id'))

    op.drop_table('engine_seat_locks')
    with op.batch_alter_table('engine_performance_seats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_performance_seats_performance_id'))
        batch_op.drop_index('ix_engine_performance_seats_perf_status')

    op.drop_table('engine_performance_seats')
    with op.batch_alter_table('engine_performance_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_performance_categories_performance_id'))

    op.drop_table('engine_performance_categories')
    with op.batch_alter_table('engine_orders', schema=None) as batch_op:
        batch_op.drop_index('uq_engine_orders_org_external_ref', postgresql_where=sa.text('external_ref IS NOT NULL'), sqlite_where=sa.text('external_ref IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_engine_orders_status'))
        batch_op.drop_index(batch_op.f('ix_engine_orders_performance_id'))
        batch_op.drop_index(batch_op.f('ix_engine_orders_organization_id'))
        batch_op.drop_index(batch_op.f('ix_engine_orders_expires_at'))

    op.drop_table('engine_orders')
    with op.batch_alter_table('engine_performances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_performances_status'))
        batch_op.drop_index(batch_op.f('ix_engine_performances_starts_at'))
        batch_op.drop_index(batch_op.f('ix_engine_performances_layout_version_id'))
        batch_op.drop_index(batch_op.f('ix_engine_performances_event_id'))

    op.drop_table('engine_performances')
    with op.batch_alter_table('engine_layout_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_layout_versions_venue_layout_id'))
        batch_op.drop_index(batch_op.f('ix_engine_layout_versions_created_by_user_id'))

    op.drop_table('engine_layout_versions')
    with op.batch_alter_table('engine_webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_webhook_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_engine_webhook_deliveries_endpoint_id'))

    op.drop_table('engine_webhook_deliveries')
    with op.batch_alter_table('engine_venue_layouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_venue_layouts_venue_id'))

    op.drop_table('engine_venue_layouts')
    with op.batch_alter_table('engine_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_events_venue_id'))
        batch_op.drop_index(batch_op.f('ix_engine_events_status'))
        batch_op.drop_index(batch_op.f('ix_engine_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_engine_events_category'))

    op.drop_table('engine_events')
    with op.batch_alter_table('engine_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_audit_log_organization_id'))
        batch_op.drop_index(batch_op.f('ix_engine_audit_log_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_engine_audit_log_action'))

    op.drop_table('engine_audit_log')
    with op.batch_alter_table('engine_webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_webhook_endpoints_organization_id'))

    op.drop_table('engine_webhook_endpoints')
    with op.batch_alter_table('engine_venues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_venues_organization_id'))

    op.drop_table('engine_venues')
    with op.batch_alter_table('engine_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_engine_memberships_organization_id'))

    op.drop_table('engine_memberships')
    with op.batch_alter_table('engine_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_api_keys_organization_id'))
        batch_op.drop_index(batch_op.f('ix_engine_api_keys_key_prefix'))

    op.drop_table('engine_api_keys')
    with op.batch_alter_table('engine_organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_organizations_slug'))

    op.drop_table('engine_organizations')
    # ### end Alembic commands ###
