"""Kursi Engine ORM models (Phase 1a) - see docs/engine-phase1-schema-spec.md.

COEXISTENCE WITH THE LEGACY SCHEMA
----------------------------------
A legacy `events` table already exists and is read by the frozen marketplace, so the
Engine's own `events` table would collide with it. Every table defined here therefore
carries an ``engine_`` prefix (``engine_events``, ``engine_orders``, ...). The legacy
tables in `app/models.py` are untouched by this module.

Three tables here intentionally point *into* the legacy schema: `users` is shared
between both worlds per spec 1, so `engine_memberships.user_id`,
`engine_layout_versions.created_by_user_id`, `engine_tickets.checked_in_by_user_id`
and `engine_audit_log.actor_user_id` are FKs onto the existing `users.id`. Note that
`users.id` is INTEGER (legacy), not BIGINT, so those columns use Integer to match.

PORTABILITY
-----------
Production is PostgreSQL; the test harness defaults to SQLite (see TESTING.md). Every
Postgres-specific type is declared with a SQLite variant so the whole schema is
creatable on both:
    JSONB    -> JSON      (SQLite)
    TEXT[]   -> JSON      (SQLite)
    BIGINT   -> INTEGER   (SQLite, so Identity PKs autoincrement via the rowid alias)
`Identity()` renders as BIGINT GENERATED BY DEFAULT AS IDENTITY on Postgres and is
ignored by SQLite.

MONEY
-----
All money is an integer minor-unit amount plus an ISO currency, per spec 5. The
`MinorAmount` type below *rejects* floats and Decimals outright rather than letting the
driver silently round them - see its docstring.
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    CHAR,
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    Identity,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.types import JSON, TypeDecorator

from app.database import Base

# Every Engine table name starts with this. Keep it in one place so the boundary
# between legacy and Engine tables is greppable.
ENGINE_PREFIX = "engine_"


# ── Portable type aliases ───────────────────────────────────────────────────
#: BIGINT on Postgres, INTEGER on SQLite (so an Identity PK autoincrements there).
BigInt = BigInteger().with_variant(Integer(), "sqlite")
#: Legacy `users.id` is INTEGER - FKs onto it must match, not BigInt.
LegacyUserId = Integer
#: timestamptz per spec conventions.
TS = DateTime(timezone=True)
#: JSONB document, degraded to JSON on SQLite.
JSONDoc = JSONB().with_variant(JSON(), "sqlite")
#: TEXT[] on Postgres, JSON array on SQLite.
TextArray = ARRAY(Text()).with_variant(JSON(), "sqlite")
#: ISO-4217 currency code.
CurrencyCode = CHAR(3)


class MinorAmount(TypeDecorator):
    """BIGINT holding an amount in minor units (fils, cents), never a float.

    Exit test 6 requires that money can never be silently rounded. A plain BIGINT
    column does not give that: PostgreSQL will happily coerce ``100.5`` to ``101``,
    and SQLite will store ``100.5`` as-is in an INTEGER-affinity column. Neither is
    acceptable for money.

    Binding is therefore the enforcement point - it runs for ORM flushes *and* for
    Core inserts, on every dialect, before the driver ever sees the value. A float or
    Decimal raises TypeError instead of being rounded. Callers converting from a
    major-unit amount must do so explicitly (KWD 5.500 -> 5500).
    """

    impl = BigInteger
    cache_ok = True

    def process_bind_param(self, value, dialect):
        if value is None:
            return None
        # bool is a subclass of int; it is never a valid money amount.
        if isinstance(value, bool):
            raise TypeError(
                f"monetary value must be an integer number of minor units, got bool: {value!r}"
            )
        if isinstance(value, int):
            return value
        raise TypeError(
            f"monetary value must be an integer number of minor units, got "
            f"{type(value).__name__}: {value!r}. Money is never a float - convert "
            f"explicitly (e.g. KWD 5.500 -> 5500)."
        )


def _enum_check(table: str, column: str, values: tuple[str, ...]) -> CheckConstraint:
    """TEXT + CHECK for an enum-like state, per spec conventions.

    Readable in plain SQL and extensible without an ALTER TYPE dance, which is why the
    spec prefers it over a native enum.
    """
    rendered = ", ".join(f"'{v}'" for v in values)
    return CheckConstraint(f"{column} IN ({rendered})", name=f"ck_{table}_{column}")


def _non_negative(table: str, column: str) -> CheckConstraint:
    return CheckConstraint(f"{column} >= 0", name=f"ck_{table}_{column}_non_negative")


def _currency_shape(table: str, column: str = "currency") -> CheckConstraint:
    """ISO-4217 codes are exactly three characters. `length()` exists on both dialects."""
    return CheckConstraint(f"length({column}) = 3", name=f"ck_{table}_{column}_len")


def _pk() -> Mapped[int]:
    return mapped_column(BigInt, Identity(), primary_key=True)


class TimestampMixin:
    """created_at / updated_at timestamptz on every Engine table, per spec conventions."""

    created_at: Mapped[datetime] = mapped_column(
        TS, server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        TS, server_default=func.now(), onupdate=func.now(), nullable=False
    )


# ── 1. Tenancy ──────────────────────────────────────────────────────────────
ORG_TYPES = ("personal", "business")
ORG_PLANS = ("personal", "business", "pro", "enterprise")
ORG_STATUSES = ("active", "suspended")


class Organization(TimestampMixin, Base):
    """A tenant. Everyone is an org (Decision 1) - personal orgs are auto-provisioned."""

    __tablename__ = f"{ENGINE_PREFIX}organizations"

    id: Mapped[int] = _pk()
    name: Mapped[str] = mapped_column(Text, nullable=False)
    name_ar: Mapped[str | None] = mapped_column(Text, nullable=True)
    slug: Mapped[str] = mapped_column(Text, nullable=False, unique=True, index=True)
    type: Mapped[str] = mapped_column(Text, nullable=False, server_default="personal")
    plan: Mapped[str] = mapped_column(Text, nullable=False, server_default="personal")
    branding: Mapped[dict] = mapped_column(
        JSONDoc, nullable=False, default=dict, server_default=text("'{}'")
    )
    settings: Mapped[dict] = mapped_column(
        JSONDoc, nullable=False, default=dict, server_default=text("'{}'")
    )
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="active")

    __table_args__ = (
        _enum_check(f"{ENGINE_PREFIX}organizations", "type", ORG_TYPES),
        # `plan` is written as an enum-like list in the spec without an explicit
        # CHECK; the Phase 1a brief asks for a CHECK on every enum-like state.
        _enum_check(f"{ENGINE_PREFIX}organizations", "plan", ORG_PLANS),
        _enum_check(f"{ENGINE_PREFIX}organizations", "status", ORG_STATUSES),
    )


MEMBERSHIP_ROLES = (
    "owner",
    "admin",
    "event_manager",
    "venue_manager",
    "box_office",
    "finance",
    "support",
    "scanner",
    "marketing",
)
MEMBERSHIP_STATUSES = ("active", "invited", "disabled")


class Membership(TimestampMixin, Base):
    """Many-to-many user <-> organization with a role. Supersedes legacy `users.role`."""

    __tablename__ = f"{ENGINE_PREFIX}memberships"

    id: Mapped[int] = _pk()
    organization_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}organizations.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    # FK into the LEGACY users table, which is shared between both worlds (spec 1).
    user_id: Mapped[int] = mapped_column(
        LegacyUserId,
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    role: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="active")

    __table_args__ = (
        UniqueConstraint(
            "organization_id", "user_id", name=f"uq_{ENGINE_PREFIX}memberships_org_user"
        ),
        _enum_check(f"{ENGINE_PREFIX}memberships", "role", MEMBERSHIP_ROLES),
        _enum_check(f"{ENGINE_PREFIX}memberships", "status", MEMBERSHIP_STATUSES),
    )


# ── 2. Venues & layouts ─────────────────────────────────────────────────────
class Venue(TimestampMixin, Base):
    __tablename__ = f"{ENGINE_PREFIX}venues"

    id: Mapped[int] = _pk()
    organization_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}organizations.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    name_ar: Mapped[str | None] = mapped_column(Text, nullable=True)
    address: Mapped[str | None] = mapped_column(Text, nullable=True)
    address_ar: Mapped[str | None] = mapped_column(Text, nullable=True)
    timezone: Mapped[str] = mapped_column(
        Text, nullable=False, server_default="Asia/Kuwait"
    )


class VenueLayout(TimestampMixin, Base):
    """A named seating arrangement of a venue, e.g. "Main Hall - Full"."""

    __tablename__ = f"{ENGINE_PREFIX}venue_layouts"

    id: Mapped[int] = _pk()
    venue_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}venues.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)


LAYOUT_VERSION_STATUSES = ("draft", "frozen")


class LayoutVersion(TimestampMixin, Base):
    """An immutable-once-frozen authoring document for a layout (spec 2).

    `layout_data` holds seats[], objects[] and categories[] in canvas units at the
    unchanged 50 px/metre contract. Once `status` is 'frozen' the database itself
    rejects any UPDATE of `layout_data`, and rejects returning to 'draft' - see the
    trigger installed by the Phase 1a migration. Edits create version_number + 1.
    """

    __tablename__ = f"{ENGINE_PREFIX}layout_versions"

    id: Mapped[int] = _pk()
    venue_layout_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}venue_layouts.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    version_number: Mapped[int] = mapped_column(Integer, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="draft")
    # Null while draft; set at the moment of freezing.
    frozen_at: Mapped[datetime | None] = mapped_column(TS, nullable=True)
    created_by_user_id: Mapped[int] = mapped_column(
        LegacyUserId,
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    layout_data: Mapped[dict] = mapped_column(JSONDoc, nullable=False)

    __table_args__ = (
        UniqueConstraint(
            "venue_layout_id",
            "version_number",
            name=f"uq_{ENGINE_PREFIX}layout_versions_layout_version",
        ),
        _enum_check(f"{ENGINE_PREFIX}layout_versions", "status", LAYOUT_VERSION_STATUSES),
    )


# ── 3. Events & performances ────────────────────────────────────────────────
EVENT_STATUSES = (
    "draft",
    "active",
    "coming_soon",
    "scheduled",
    "cancelled",
    "archived",
)


class EngineEvent(TimestampMixin, Base):
    """The Engine's event. Distinct from the legacy `events` table, which is frozen."""

    __tablename__ = f"{ENGINE_PREFIX}events"

    id: Mapped[int] = _pk()
    organization_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}organizations.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    venue_id: Mapped[int | None] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}venues.id", ondelete="RESTRICT"),
        nullable=True,
        index=True,
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    title_ar: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    description_ar: Mapped[str | None] = mapped_column(Text, nullable=True)
    artwork_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    cover_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    category: Mapped[str | None] = mapped_column(Text, nullable=True, index=True)
    # Column name is `cast` per spec; it is a reserved word, so SQLAlchemy quotes it.
    cast: Mapped[dict] = mapped_column(
        JSONDoc, nullable=False, default=dict, server_default=text("'{}'")
    )
    policies: Mapped[dict] = mapped_column(
        JSONDoc, nullable=False, default=dict, server_default=text("'{}'")
    )
    status: Mapped[str] = mapped_column(
        Text, nullable=False, server_default="draft", index=True
    )

    __table_args__ = (
        _enum_check(f"{ENGINE_PREFIX}events", "status", EVENT_STATUSES),
    )


PERFORMANCE_STATUSES = (
    "draft",
    "on_sale",
    "paused",
    "sold_out",
    "closed",
    "cancelled",
)


class Performance(TimestampMixin, Base):
    """A single dated showing. Owns its seating via an immutable layout version."""

    __tablename__ = f"{ENGINE_PREFIX}performances"

    id: Mapped[int] = _pk()
    event_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}events.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    layout_version_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}layout_versions.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    starts_at: Mapped[datetime] = mapped_column(TS, nullable=False, index=True)
    doors_open_at: Mapped[datetime | None] = mapped_column(TS, nullable=True)
    duration_minutes: Mapped[int | None] = mapped_column(Integer, nullable=True)
    sales_open_at: Mapped[datetime | None] = mapped_column(TS, nullable=True)
    sales_close_at: Mapped[datetime | None] = mapped_column(TS, nullable=True)
    box_office_close_at: Mapped[datetime | None] = mapped_column(TS, nullable=True)
    status: Mapped[str] = mapped_column(
        Text, nullable=False, server_default="draft", index=True
    )

    __table_args__ = (
        _enum_check(f"{ENGINE_PREFIX}performances", "status", PERFORMANCE_STATUSES),
    )


class PerformanceCategory(TimestampMixin, Base):
    """Per-performance pricing for a category key defined in the layout document."""

    __tablename__ = f"{ENGINE_PREFIX}performance_categories"

    id: Mapped[int] = _pk()
    performance_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}performances.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    category_key: Mapped[str] = mapped_column(Text, nullable=False)
    name: Mapped[str] = mapped_column(Text, nullable=False)
    name_ar: Mapped[str | None] = mapped_column(Text, nullable=True)
    color: Mapped[str | None] = mapped_column(Text, nullable=True)
    amount_minor: Mapped[int] = mapped_column(MinorAmount, nullable=False)
    currency: Mapped[str] = mapped_column(CurrencyCode, nullable=False)

    __table_args__ = (
        UniqueConstraint(
            "performance_id",
            "category_key",
            name=f"uq_{ENGINE_PREFIX}performance_categories_perf_key",
        ),
        _non_negative(f"{ENGINE_PREFIX}performance_categories", "amount_minor"),
        _currency_shape(f"{ENGINE_PREFIX}performance_categories"),
    )


SEAT_STATUSES = ("available", "blocked", "invitation", "reserved_internal")


class PerformanceSeat(TimestampMixin, Base):
    """The inventory row: one physical seat, for one performance.

    Deliberately has NO 'sold' or 'locked' status (spec 3). Sold is the existence of a
    live ticket; locked is the existence of an active lock. Keeping those out of this
    column is what prevents status drift between tables.
    """

    __tablename__ = f"{ENGINE_PREFIX}performance_seats"

    id: Mapped[int] = _pk()
    performance_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}performances.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    seat_uid: Mapped[str] = mapped_column(Text, nullable=False)
    section: Mapped[str | None] = mapped_column(Text, nullable=True)
    row_label: Mapped[str | None] = mapped_column(Text, nullable=True)
    seat_number: Mapped[str | None] = mapped_column(Text, nullable=True)
    label: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Canvas units at 50 px/metre - the coordinate contract is unchanged.
    x: Mapped[float | None] = mapped_column(Float, nullable=True)
    y: Mapped[float | None] = mapped_column(Float, nullable=True)
    category_key: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="available")
    price_override_minor: Mapped[int | None] = mapped_column(MinorAmount, nullable=True)
    currency: Mapped[str | None] = mapped_column(CurrencyCode, nullable=True)
    accessibility: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )

    __table_args__ = (
        UniqueConstraint(
            "performance_id",
            "seat_uid",
            name=f"uq_{ENGINE_PREFIX}performance_seats_perf_seat_uid",
        ),
        Index(f"ix_{ENGINE_PREFIX}performance_seats_perf_status", "performance_id", "status"),
        _enum_check(f"{ENGINE_PREFIX}performance_seats", "status", SEAT_STATUSES),
        _non_negative(f"{ENGINE_PREFIX}performance_seats", "price_override_minor"),
    )


# ── 4. Checkout & locking ───────────────────────────────────────────────────
ORDER_CHANNELS = ("marketplace", "api", "box_office", "comp", "invitation")
ORDER_STATUSES = ("draft", "awaiting_payment", "completed", "expired", "cancelled")


class Order(TimestampMixin, Base):
    """A checkout session. `expires_at` is authoritative for all of its locks."""

    __tablename__ = f"{ENGINE_PREFIX}orders"

    id: Mapped[int] = _pk()
    organization_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}organizations.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    performance_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}performances.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    channel: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(
        Text, nullable=False, server_default="draft", index=True
    )
    customer_name: Mapped[str | None] = mapped_column(Text, nullable=True)
    customer_email: Mapped[str | None] = mapped_column(Text, nullable=True)
    customer_phone: Mapped[str | None] = mapped_column(Text, nullable=True)
    expires_at: Mapped[datetime | None] = mapped_column(TS, nullable=True, index=True)
    # The single permitted +4:00 extension (Decision 3).
    extended: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    subtotal_minor: Mapped[int] = mapped_column(
        MinorAmount, nullable=False, server_default=text("0")
    )
    fees_minor: Mapped[int] = mapped_column(
        MinorAmount, nullable=False, server_default=text("0")
    )
    discount_minor: Mapped[int] = mapped_column(
        MinorAmount, nullable=False, server_default=text("0")
    )
    total_minor: Mapped[int] = mapped_column(
        MinorAmount, nullable=False, server_default=text("0")
    )
    currency: Mapped[str] = mapped_column(CurrencyCode, nullable=False)
    # Client/API idempotency key - unique per org, but many orders may have none.
    external_ref: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        _enum_check(f"{ENGINE_PREFIX}orders", "channel", ORDER_CHANNELS),
        _enum_check(f"{ENGINE_PREFIX}orders", "status", ORDER_STATUSES),
        _non_negative(f"{ENGINE_PREFIX}orders", "subtotal_minor"),
        _non_negative(f"{ENGINE_PREFIX}orders", "fees_minor"),
        _non_negative(f"{ENGINE_PREFIX}orders", "discount_minor"),
        _non_negative(f"{ENGINE_PREFIX}orders", "total_minor"),
        _currency_shape(f"{ENGINE_PREFIX}orders"),
        # INVARIANT: external_ref unique per organization, but only where present.
        Index(
            f"uq_{ENGINE_PREFIX}orders_org_external_ref",
            "organization_id",
            "external_ref",
            unique=True,
            postgresql_where=text("external_ref IS NOT NULL"),
            sqlite_where=text("external_ref IS NOT NULL"),
        ),
    )


class SeatLock(TimestampMixin, Base):
    """A held seat. The partial unique index below is the race arbiter (spec 4).

    A lock is ACTIVE iff released_at IS NULL AND its order has not expired AND that
    order is still in ('draft','awaiting_payment'). Nothing sweeps for correctness.
    """

    __tablename__ = f"{ENGINE_PREFIX}seat_locks"

    id: Mapped[int] = _pk()
    order_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}orders.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    performance_seat_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}performance_seats.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    released_at: Mapped[datetime | None] = mapped_column(TS, nullable=True)

    __table_args__ = (
        # INVARIANT 1: at most one unreleased lock per seat. Two racing INSERTs, one
        # winner - decided by the database, not by application code.
        Index(
            f"uq_{ENGINE_PREFIX}seat_locks_active_seat",
            "performance_seat_id",
            unique=True,
            postgresql_where=text("released_at IS NULL"),
            sqlite_where=text("released_at IS NULL"),
        ),
    )


# ── 5. Tickets ──────────────────────────────────────────────────────────────
TICKET_STATUSES = ("issued", "checked_in", "cancelled", "refunded")


class Ticket(TimestampMixin, Base):
    """A sold seat. `id` is stable for life; credentials rotate around it (Decision 4)."""

    __tablename__ = f"{ENGINE_PREFIX}tickets"

    id: Mapped[int] = _pk()
    order_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}orders.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    organization_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}organizations.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    performance_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}performances.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    performance_seat_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}performance_seats.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default="issued")
    credential_version: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("1")
    )
    credential_hash: Mapped[str | None] = mapped_column(Text, nullable=True)
    issued_at: Mapped[datetime] = mapped_column(
        TS, nullable=False, server_default=func.now()
    )
    checked_in_at: Mapped[datetime | None] = mapped_column(TS, nullable=True)
    # SET NULL: the check-in record must outlive the staff account that performed it.
    checked_in_by_user_id: Mapped[int | None] = mapped_column(
        LegacyUserId, ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    amount_paid_minor: Mapped[int] = mapped_column(MinorAmount, nullable=False)
    currency: Mapped[str] = mapped_column(CurrencyCode, nullable=False)

    __table_args__ = (
        _enum_check(f"{ENGINE_PREFIX}tickets", "status", TICKET_STATUSES),
        _non_negative(f"{ENGINE_PREFIX}tickets", "amount_paid_minor"),
        _currency_shape(f"{ENGINE_PREFIX}tickets"),
        CheckConstraint(
            "credential_version >= 1",
            name=f"ck_{ENGINE_PREFIX}tickets_credential_version_positive",
        ),
        # INVARIANT 2: the never-double-sell backstop. At most one live ticket per
        # seat; cancelled/refunded tickets drop out of the index and free the seat.
        Index(
            f"uq_{ENGINE_PREFIX}tickets_live_seat",
            "performance_seat_id",
            unique=True,
            postgresql_where=text("status IN ('issued', 'checked_in')"),
            sqlite_where=text("status IN ('issued', 'checked_in')"),
        ),
    )


# ── 6. Usage, audit, keys, webhooks ─────────────────────────────────────────
class UsageEvent(TimestampMixin, Base):
    """One row per issued ticket, never deleted - billing is monotonic (Decision 4)."""

    __tablename__ = f"{ENGINE_PREFIX}usage_events"

    id: Mapped[int] = _pk()
    organization_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}organizations.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    # UNIQUE: one usage event per ticket, so re-issuing can never double-bill.
    # RESTRICT: a ticket with usage recorded must not be deletable.
    ticket_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}tickets.id", ondelete="RESTRICT"),
        nullable=False,
        unique=True,
    )
    occurred_at: Mapped[datetime] = mapped_column(
        TS, nullable=False, server_default=func.now(), index=True
    )


API_KEY_ENVIRONMENTS = ("sandbox", "production")


class ApiKey(TimestampMixin, Base):
    __tablename__ = f"{ENGINE_PREFIX}api_keys"

    id: Mapped[int] = _pk()
    organization_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}organizations.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    key_prefix: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    key_hash: Mapped[str] = mapped_column(Text, nullable=False)
    environment: Mapped[str] = mapped_column(Text, nullable=False)
    scopes: Mapped[list] = mapped_column(TextArray, nullable=False, default=list)
    last_used_at: Mapped[datetime | None] = mapped_column(TS, nullable=True)
    revoked_at: Mapped[datetime | None] = mapped_column(TS, nullable=True)

    __table_args__ = (
        _enum_check(f"{ENGINE_PREFIX}api_keys", "environment", API_KEY_ENVIRONMENTS),
    )


class AuditLog(TimestampMixin, Base):
    """Append-only. Actor FKs are SET NULL so the record outlives the actor."""

    __tablename__ = f"{ENGINE_PREFIX}audit_log"

    id: Mapped[int] = _pk()
    organization_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}organizations.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    actor_user_id: Mapped[int | None] = mapped_column(
        LegacyUserId, ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    actor_api_key_id: Mapped[int | None] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}api_keys.id", ondelete="SET NULL"),
        nullable=True,
    )
    action: Mapped[str] = mapped_column(Text, nullable=False, index=True)
    entity_type: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Spec does not type this; every Engine PK is BIGINT, so BIGINT it is.
    entity_id: Mapped[int | None] = mapped_column(BigInt, nullable=True)
    data: Mapped[dict] = mapped_column(
        JSONDoc, nullable=False, default=dict, server_default=text("'{}'")
    )
    occurred_at: Mapped[datetime] = mapped_column(
        TS, nullable=False, server_default=func.now(), index=True
    )


class WebhookEndpoint(TimestampMixin, Base):
    __tablename__ = f"{ENGINE_PREFIX}webhook_endpoints"

    id: Mapped[int] = _pk()
    organization_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}organizations.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    url: Mapped[str] = mapped_column(Text, nullable=False)
    secret: Mapped[str] = mapped_column(Text, nullable=False)
    events: Mapped[list] = mapped_column(TextArray, nullable=False, default=list)
    active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )


WEBHOOK_DELIVERY_STATUSES = ("pending", "delivered", "failed")


class WebhookDelivery(TimestampMixin, Base):
    """CASCADE is the one deliberate exception to RESTRICT: a delivery attempt has no
    meaning once its endpoint is gone, and deliveries are transient operational rows."""

    __tablename__ = f"{ENGINE_PREFIX}webhook_deliveries"

    id: Mapped[int] = _pk()
    endpoint_id: Mapped[int] = mapped_column(
        BigInt,
        ForeignKey(f"{ENGINE_PREFIX}webhook_endpoints.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    event_type: Mapped[str] = mapped_column(Text, nullable=False)
    payload: Mapped[dict] = mapped_column(
        JSONDoc, nullable=False, default=dict, server_default=text("'{}'")
    )
    status: Mapped[str] = mapped_column(
        Text, nullable=False, server_default="pending", index=True
    )
    attempts: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )
    last_attempt_at: Mapped[datetime | None] = mapped_column(TS, nullable=True)

    __table_args__ = (
        _enum_check(
            f"{ENGINE_PREFIX}webhook_deliveries", "status", WEBHOOK_DELIVERY_STATUSES
        ),
        CheckConstraint(
            "attempts >= 0", name=f"ck_{ENGINE_PREFIX}webhook_deliveries_attempts"
        ),
    )


#: Every Engine table, in dependency order (parents first). Used by the migration and
#: by tests that need to clear Engine data without touching legacy tables.
ENGINE_TABLES: tuple[str, ...] = (
    Organization.__tablename__,
    Membership.__tablename__,
    Venue.__tablename__,
    VenueLayout.__tablename__,
    LayoutVersion.__tablename__,
    EngineEvent.__tablename__,
    Performance.__tablename__,
    PerformanceCategory.__tablename__,
    PerformanceSeat.__tablename__,
    Order.__tablename__,
    SeatLock.__tablename__,
    Ticket.__tablename__,
    ApiKey.__tablename__,
    UsageEvent.__tablename__,
    AuditLog.__tablename__,
    WebhookEndpoint.__tablename__,
    WebhookDelivery.__tablename__,
)
